name: Build and Release APK

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.2'
        channel: 'stable'
        cache: true
        
    - name: Cache pub dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          avoidance_game/.dart_tool
          avoidance_game/build
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-
          
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
        
    - name: Get dependencies
      run: |
        cd avoidance_game
        flutter pub get
        
    - name: Build APK
      run: |
        cd avoidance_game
        flutter build apk --release
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: avoidance_game/build/app/outputs/flutter-apk/app-release.apk
        retention-days: 5

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download APK artifact
      uses: actions/download-artifact@v4
      with:
        name: release-apk
        
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${{ steps.get_version.outputs.VERSION }}
        
        # Create release notes
        cat << EOF > release_notes.md
        # Avoidance Game ${VERSION}
        
        ## 📱 Installation
        1. Download the APK file: \`avoidance-game-${VERSION}.apk\`
        2. Enable "Install from Unknown Sources" in your Android settings
        3. Open the APK file to install
        4. Launch "Avoidance" from your app drawer
        
        ## 🎮 Game Modes
        - **Easy**: Single blue ship avoiding blue waves
        - **Medium**: Dual ship control (blue and orange)
        - **Hard**: Dual ships with shield system and power-ups
        - **Ultra**: Astronaut with gyroscope controls and oxygen system
        
        ## 📝 Changelog
        See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
        EOF
        
        # Create release using GitHub CLI
        gh release create ${VERSION} \
          --title "Avoidance Game ${VERSION}" \
          --notes-file release_notes.md \
          ./app-release.apk#avoidance-game-${VERSION}.apk