name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    name: Build and Test APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.2'
        channel: 'stable'
        
    - name: Get dependencies
      run: |
        cd avoidance_game
        flutter pub get
        
    - name: Run tests
      run: |
        cd avoidance_game
        flutter test || true # Don't fail if no tests exist
        
    - name: Analyze code
      run: |
        cd avoidance_game
        flutter analyze || true # Don't fail on warnings
        
    - name: Build Debug APK
      run: |
        cd avoidance_game
        flutter build apk --debug
        
    - name: Build Release APK
      run: |
        cd avoidance_game
        flutter build apk --release
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: avoidance_game/build/app/outputs/flutter-apk/app-debug.apk
        retention-days: 1
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: avoidance_game/build/app/outputs/flutter-apk/app-release.apk
        retention-days: 1